apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aiops-platform
  title: Plataforma AIOps
  description: Stack de observabilidade no EKS com Prometheus, Grafana e Loki, construída por agentes de IA.
  annotations:
    github.com/project-slug: Alves0611/aiops-platform
    backstage.io/techdocs-ref: dir:.
  tags:
    - terraform
    - kubernetes
    - observability
    - aws
spec:
  type: iac-module
  lifecycle: production
  owner: user:alves0611
  system: observability
