apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traffic-simulator
  labels:
    app: traffic-simulator
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: traffic-simulator
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
